# api-service 全局配置
server:
   mode: debug
   healthz: true

# http 配置
insecure:
  bind-address: 0.0.0.0
  bind-port: 8181

feature:
  enable-metrics: true # 开启 metrics, router:  /metrics
  profiling: true # 开启性能分析, 可以通过 <host>:<port>/debug/pprof/地址查看程序栈、线程等系统信息，默认值为 true
