# api-service 全局配置
server:
   mode: debug # 运行模式, release/debug
   healthz: true
   max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

# http 配置
insecure:
  bind-address: 0.0.0.0
  bind-port: 8181

# metrics 配置
feature:
  enable-metrics: true # 开启 metrics, router:  /metrics
  profiling: false # 开启性能分析, 可以通过 <host>:<port>/debug/pprof/地址查看程序栈、线程等系统信息，默认值为 true


# 日志配置

log:
  name: apiserver # Logger的名字
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: json # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths: log/apiserver.log,stdout # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件。
  error-output-paths: log/apiserver.error.log # zap内部(非业务)错误日志输出路径，多个输出，逗号分开

